// Generated by build/write_buildflag_header.py
// From "//base:synchronization_flags"

#ifndef BASE_SYNCHRONIZATION_SYNCHRONIZATION_FLAGS_H_
#define BASE_SYNCHRONIZATION_SYNCHRONIZATION_FLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ENABLE_MUTEX_PRIORITY_INHERITANCE() (0)

#endif  // BASE_SYNCHRONIZATION_SYNCHRONIZATION_FLAGS_H_
