// Generated by build/write_buildflag_header.py
// From "//base:cfi_flags"

#ifndef BASE_CFI_FLAGS_H_
#define BASE_CFI_FLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_CFI_CAST_CHECK() (false && false)
#define BUILDFLAG_INTERNAL_CFI_ICALL_CHECK() (false && false)
#define BUILDFLAG_INTERNAL_CFI_ENFORCEMENT_TRAP() (false && !false)
#define BUILDFLAG_INTERNAL_CFI_ENFORCEMENT_DIAGNOSTIC() (false && false && !false)

#endif  // BASE_CFI_FLAGS_H_
